version: '3.8'

name: 'nestjs-rattrapage'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_DB: nestjs-rattrapage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
